services:
  - type: web
    name: odoo17
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ODOO_DB_HOST
        value: render-postgres-xyz.internal
      - key: ODOO_DB_PORT
        value: "5432"
      - key: ODOO_DB_USER
        value: odoo
      - key: ODOO_DB_PASSWORD
        value: strongpassword
      - key: ODOO_DB_NAME
        value: odoo17
      - key: ODOO_ADMIN_PASSWORD
        value: YourStrongAdminPassword
