services:
  - type: web
    name: odoo17-faris
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_HOST
        value: dpg-d459apadbo4c73fnv440-a.oregon-postgres.render.com
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_USER
        value: odoo_db_wzxu_user
      - key: DATABASE_PASSWORD
        value: V8X1y2eagAe4lkoZMgOEP0nmNVGqwyXv
      - key: DATABASE_NAME
        value: odoo_db_wzxu
      - key: ODOO_ADMIN_PASSWORD
        value: GF27-faris